//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// There are no comments for AirlineSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirlineSingle")]
    public partial class AirlineSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Airline>
    {
        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AirlineSingle object.
        /// </summary>
        public AirlineSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Airline> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Airline in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AirlineCode
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("AirlineCode")]
    [global::Microsoft.OData.Client.EntitySet("Airlines")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Airline")]
    public partial class Airline : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Airline object.
        /// </summary>
        /// <param name="airlineCode">Initial value of AirlineCode.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Airline CreateAirline(string airlineCode, string name)
        {
            Airline airline = new Airline();
            airline.AirlineCode = airlineCode;
            airline.Name = name;
            return airline;
        }
        /// <summary>
        /// There are no comments for Property AirlineCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AirlineCode")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "AirlineCode is required.")]
        public virtual string AirlineCode
        {
            get
            {
                return this._AirlineCode;
            }
            set
            {
                this.OnAirlineCodeChanging(value);
                this._AirlineCode = value;
                this.OnAirlineCodeChanged();
                this.OnPropertyChanged("AirlineCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AirlineCode;
        partial void OnAirlineCodeChanging(string value);
        partial void OnAirlineCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Name is required.")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
