//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// There are no comments for AirportLocation in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AirportLocation")]
    public partial class AirportLocation : Location
    {
        /// <summary>
        /// Create a new AirportLocation object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="city">Initial value of City.</param>
        /// <param name="loc">Initial value of Loc.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static AirportLocation CreateAirportLocation(string address, global::Microsoft.OData.SampleService.Models.TripPin.City city, global::Microsoft.Spatial.GeographyPoint loc)
        {
            AirportLocation airportLocation = new AirportLocation();
            airportLocation.Address = address;
            if ((city == null))
            {
                throw new global::System.ArgumentNullException("city");
            }
            airportLocation.City = city;
            airportLocation.Loc = loc;
            return airportLocation;
        }
        /// <summary>
        /// There are no comments for Property Loc in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Loc")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Loc is required.")]
        public virtual global::Microsoft.Spatial.GeographyPoint Loc
        {
            get
            {
                return this._Loc;
            }
            set
            {
                this.OnLocChanging(value);
                this._Loc = value;
                this.OnLocChanged();
                this.OnPropertyChanged("Loc");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Spatial.GeographyPoint _Loc;
        partial void OnLocChanging(global::Microsoft.Spatial.GeographyPoint value);
        partial void OnLocChanged();
    }
}
