//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// There are no comments for EventLocation in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EventLocation")]
    public partial class EventLocation : Location
    {
        /// <summary>
        /// Create a new EventLocation object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="city">Initial value of City.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static EventLocation CreateEventLocation(string address, global::Microsoft.OData.SampleService.Models.TripPin.City city)
        {
            EventLocation eventLocation = new EventLocation();
            eventLocation.Address = address;
            if ((city == null))
            {
                throw new global::System.ArgumentNullException("city");
            }
            eventLocation.City = city;
            return eventLocation;
        }
        /// <summary>
        /// There are no comments for Property BuildingInfo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BuildingInfo")]
        public virtual string BuildingInfo
        {
            get
            {
                return this._BuildingInfo;
            }
            set
            {
                this.OnBuildingInfoChanging(value);
                this._BuildingInfo = value;
                this.OnBuildingInfoChanged();
                this.OnPropertyChanged("BuildingInfo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BuildingInfo;
        partial void OnBuildingInfoChanging(string value);
        partial void OnBuildingInfoChanged();
    }
}
