//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Photo as global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Photo> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Photo as global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Photo> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.PhotoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Person as global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Person> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Person as global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Person> _source,
            string userName)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.PersonSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Airline as global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Airline> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Airline as global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="airlineCode">The value of airlineCode</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Airline> _source,
            string airlineCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "AirlineCode", airlineCode }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Airport as global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Airport> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Airport as global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="icaoCode">The value of icaoCode</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Airport> _source,
            string icaoCode)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "IcaoCode", icaoCode }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.AirportSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PlanItem as global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.PlanItem> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PlanItem as global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.PlanItem> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.PlanItemSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation as global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation as global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PlanItem to its derived type global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle CastToPublicTransportation(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation> query = _source.CastTo<global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation>();
            return new global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportationSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Flight as global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Flight> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Flight as global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Flight> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation to its derived type global::Microsoft.OData.SampleService.Models.TripPin.Flight
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle CastToFlight(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.PublicTransportation> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Flight> query = _source.CastTo<global::Microsoft.OData.SampleService.Models.TripPin.Flight>();
            return new global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PlanItem to its derived type global::Microsoft.OData.SampleService.Models.TripPin.Flight
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle CastToFlight(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Flight> query = _source.CastTo<global::Microsoft.OData.SampleService.Models.TripPin.Flight>();
            return new global::Microsoft.OData.SampleService.Models.TripPin.FlightSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Event as global::Microsoft.OData.SampleService.Models.TripPin.EventSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.EventSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Event> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.EventSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Event as global::Microsoft.OData.SampleService.Models.TripPin.EventSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="planItemId">The value of planItemId</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.EventSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Event> _source,
            int planItemId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "PlanItemId", planItemId }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.EventSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Microsoft.OData.SampleService.Models.TripPin.PlanItem to its derived type global::Microsoft.OData.SampleService.Models.TripPin.Event
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.EventSingle CastToEvent(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.PlanItem> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Event> query = _source.CastTo<global::Microsoft.OData.SampleService.Models.TripPin.Event>();
            return new global::Microsoft.OData.SampleService.Models.TripPin.EventSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Trip as global::Microsoft.OData.SampleService.Models.TripPin.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Trip> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Microsoft.OData.SampleService.Models.TripPin.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Microsoft.OData.SampleService.Models.TripPin.Trip as global::Microsoft.OData.SampleService.Models.TripPin.TripSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="tripId">The value of tripId</param>
        public static global::Microsoft.OData.SampleService.Models.TripPin.TripSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Trip> _source,
            int tripId)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "TripId", tripId }
            };
            return new global::Microsoft.OData.SampleService.Models.TripPin.TripSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// There are no comments for GetFavoriteAirline in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetFavoriteAirline")]
        public static global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle GetFavoriteAirline(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Person> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.SampleService.Models.TripPin.AirlineSingle(_source.CreateFunctionQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Airline>("Microsoft.OData.SampleService.Models.TripPin.GetFavoriteAirline", true));
        }
        /// <summary>
        /// There are no comments for GetInvolvedPeople in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetInvolvedPeople")]
        public static global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Person> GetInvolvedPeople(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Trip> _source)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuery<global::Microsoft.OData.SampleService.Models.TripPin.Person>("Microsoft.OData.SampleService.Models.TripPin.GetInvolvedPeople", true);
        }
        /// <summary>
        /// There are no comments for GetFriendsTrips in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetFriendsTrips")]
        public static global::Microsoft.OData.Client.DataServiceQuery<global::Microsoft.OData.SampleService.Models.TripPin.Trip> GetFriendsTrips(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Person> _source, string userName)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return _source.CreateFunctionQuery<global::Microsoft.OData.SampleService.Models.TripPin.Trip>("Microsoft.OData.SampleService.Models.TripPin.GetFriendsTrips", true, new global::Microsoft.OData.Client.UriOperationParameter("userName", userName));
        }
        /// <summary>
        /// There are no comments for ShareTrip in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("ShareTrip")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery ShareTrip(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Microsoft.OData.SampleService.Models.TripPin.Person> _source, string userName, int tripId)
        {
            if (!_source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(_source.Context, _source.AppendRequestUri("Microsoft.OData.SampleService.Models.TripPin.ShareTrip"), new global::Microsoft.OData.Client.BodyOperationParameter("userName", userName),
                    new global::Microsoft.OData.Client.BodyOperationParameter("tripId", tripId));
        }
    }
}
