//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// There are no comments for PersonGender in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PersonGender")]
    public enum PersonGender
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Male")]
        Male = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Female")]
        Female = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Unknown")]
        Unknown = 2
    }
}
