//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 09/26/21 10:26:55 PM
namespace Microsoft.OData.SampleService.Models.TripPin
{
    /// <summary>
    /// There are no comments for PlanItemSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItemSingle")]
    public partial class PlanItemSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PlanItem>
    {
        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PlanItemSingle object.
        /// </summary>
        public PlanItemSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PlanItem> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PlanItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlanItemId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("PlanItemId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItem")]
    public partial class PlanItem : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PlanItem object.
        /// </summary>
        /// <param name="planItemId">Initial value of PlanItemId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PlanItem CreatePlanItem(int planItemId)
        {
            PlanItem planItem = new PlanItem();
            planItem.PlanItemId = planItemId;
            return planItem;
        }
        /// <summary>
        /// There are no comments for Property PlanItemId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PlanItemId")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "PlanItemId is required.")]
        public virtual int PlanItemId
        {
            get
            {
                return this._PlanItemId;
            }
            set
            {
                this.OnPlanItemIdChanging(value);
                this._PlanItemId = value;
                this.OnPlanItemIdChanged();
                this.OnPropertyChanged("PlanItemId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _PlanItemId;
        partial void OnPlanItemIdChanging(int value);
        partial void OnPlanItemIdChanged();
        /// <summary>
        /// There are no comments for Property ConfirmationCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConfirmationCode")]
        public virtual string ConfirmationCode
        {
            get
            {
                return this._ConfirmationCode;
            }
            set
            {
                this.OnConfirmationCodeChanging(value);
                this._ConfirmationCode = value;
                this.OnConfirmationCodeChanged();
                this.OnPropertyChanged("ConfirmationCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ConfirmationCode;
        partial void OnConfirmationCodeChanging(string value);
        partial void OnConfirmationCodeChanged();
        /// <summary>
        /// There are no comments for Property StartsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StartsAt")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> StartsAt
        {
            get
            {
                return this._StartsAt;
            }
            set
            {
                this.OnStartsAtChanging(value);
                this._StartsAt = value;
                this.OnStartsAtChanged();
                this.OnPropertyChanged("StartsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _StartsAt;
        partial void OnStartsAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnStartsAtChanged();
        /// <summary>
        /// There are no comments for Property EndsAt in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EndsAt")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> EndsAt
        {
            get
            {
                return this._EndsAt;
            }
            set
            {
                this.OnEndsAtChanging(value);
                this._EndsAt = value;
                this.OnEndsAtChanged();
                this.OnPropertyChanged("EndsAt");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _EndsAt;
        partial void OnEndsAtChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnEndsAtChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Duration")]
        public virtual global::System.Nullable<global::System.TimeSpan> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.TimeSpan> _Duration;
        partial void OnDurationChanging(global::System.Nullable<global::System.TimeSpan> value);
        partial void OnDurationChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
